version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: financa_db
    restart: always
    environment:
      POSTGRES_USER: financa_user
      POSTGRES_PASSWORD: financa_password
      POSTGRES_DB: financa_db
    volumes:
      - financa_db_data:/var/lib/postgresql/data
    networks:
      - financa_network

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: financa_web
    restart: always
    ports:
      - "3005:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://financa_user:financa_password@db:5432/financa_db?schema=public
      - PLUGGY_CLIENT_ID=${PLUGGY_CLIENT_ID}
      - PLUGGY_CLIENT_SECRET=${PLUGGY_CLIENT_SECRET}
    depends_on:
      - db
    networks:
      - financa_network

volumes:
  financa_db_data:

networks:
  financa_network:
    driver: bridge
